a = int(input("Enter integer : "))
b = input("Enter string : ")
c = float(input("Enter float : "))
d = bool(input("Enter a boolean value : "))
e = complex(input("Entr a complex number : "))
print("a is  : ",type(a))
print("b is : ",type(b))
print("c is : ",type(c))
print("d is : ",type(d))
print("e is : ",type(e))